export { default as Close } from './close.svg?react'
export { default as Copy } from './Copy.svg?react'
export { default as Slippage } from './slippage.svg?react'
export { default as Wallet } from './wallet.svg?react'
export { default as Search } from './search.svg?react'
export { default as SelectorArrow } from './selectorArrow.svg?react'
